// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace data.Migrations
{
    [DbContext(typeof(_ApplicationConnectionDb))]
    [Migration("20260313210330_44")]
    partial class _44
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("CompressedSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileExtensionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePhysicalPathRoad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileStoredName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeletedStatu")
                        .HasColumnType("bit");

                    b.Property<long?>("OriginalSize")
                        .HasColumnType("bigint");

                    b.Property<string>("OrjFilePhysicalPathRoad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrjFileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("data.Addresses", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("data.CategoriesAz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CategoriesAz");
                });

            modelBuilder.Entity("data.CategoriesDe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CategoriesDe");
                });

            modelBuilder.Entity("data.CategoriesEn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CategoriesEn");
                });

            modelBuilder.Entity("data.CategoriesEs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CategoriesEs");
                });

            modelBuilder.Entity("data.CategoriesFr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CategoriesFr");
                });

            modelBuilder.Entity("data.CategoriesHi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CategoriesHi");
                });

            modelBuilder.Entity("data.CategoriesPt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CategoriesPt");
                });

            modelBuilder.Entity("data.CategoriesRu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CategoriesRu");
                });

            modelBuilder.Entity("data.CategoriesTr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CategoriesTr");
                });

            modelBuilder.Entity("data.CategoriesZh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CategoriesZh");
                });

            modelBuilder.Entity("data.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeletedBySender")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedBySenderAndReceiver")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ChatMessage");
                });

            modelBuilder.Entity("data.Cities", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("country_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("country_id")
                        .HasColumnType("int");

                    b.Property<string>("country_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("latitude")
                        .HasColumnType("float");

                    b.Property<int?>("level")
                        .HasColumnType("int");

                    b.Property<double?>("longitude")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("native")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("parent_id")
                        .HasColumnType("int");

                    b.Property<long?>("population")
                        .HasColumnType("bigint");

                    b.Property<string>("state_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("state_id")
                        .HasColumnType("int");

                    b.Property<string>("state_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("timezone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("translations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wikiDataId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("data.Country", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<long?>("area_sq_km")
                        .HasColumnType("bigint");

                    b.Property<string>("capital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currency_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currency_symbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emoji")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emojiU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("flag")
                        .HasColumnType("bit");

                    b.Property<long?>("gdp")
                        .HasColumnType("bigint");

                    b.Property<string>("iso2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("iso3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("latitude")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal?>("longitude")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("native")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numeric_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phonecode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("population")
                        .HasColumnType("bigint");

                    b.Property<string>("postal_code_format")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("postal_code_regex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("region_id")
                        .HasColumnType("int");

                    b.Property<string>("subregion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("subregion_id")
                        .HasColumnType("int");

                    b.Property<string>("timezones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tld")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("translations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("wikiDataId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("data.EmailHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Attachments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromWhom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToWho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmailHistory");
                });

            modelBuilder.Entity("data.FriendShip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Block")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("FriendShip");
                });

            modelBuilder.Entity("data.ItemGallery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ItemAddDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MediaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ItemGallery");
                });

            modelBuilder.Entity("data.Languages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Iso2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Iso3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NativeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("data.LoginTry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AttemptDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Browser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<string>("Platform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("LoginTry");
                });

            modelBuilder.Entity("data.Logs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Languages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageNameSpaceTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("data.Pricing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DiscountPriceAZN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiscountPriceEUR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiscountPriceTL")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiscountPriceUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceAZN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceEUR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceTL")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PriceTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PriceUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Pricing");
                });

            modelBuilder.Entity("data.Regions", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("flag")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("translations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_at")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("wikiDataId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("data.States", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("country_code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("country_code");

                    b.Property<int?>("country_id")
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<string>("country_name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("country_name");

                    b.Property<string>("fips_code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("fips_code");

                    b.Property<string>("iso2")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("iso2");

                    b.Property<string>("iso3166_2")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("iso3166_2");

                    b.Property<decimal>("latitude")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<int?>("level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<decimal>("longitude")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<string>("name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("native")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("native");

                    b.Property<int?>("parent_id")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<long?>("population")
                        .HasColumnType("bigint")
                        .HasColumnName("population");

                    b.Property<string>("timezone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("timezone");

                    b.Property<string>("translations")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("translations");

                    b.Property<string>("type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.Property<string>("wikiDataId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("wikiDataId");

                    b.HasKey("id");

                    b.ToTable("States");
                });

            modelBuilder.Entity("data.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActivityCertificate")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("AdminPermissionPending")
                        .HasColumnType("bit");

                    b.Property<Guid?>("AuthorizedPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BankAccountConfirmation")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BankStatement")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CertificateOfIncorporation")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CustomsRegistration")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("IsActiveDateAdmin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IsActiveDateVendor")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActiveStateAdmin")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsActiveStateVendor")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LetterOfAuthorization")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProofOfBusinessAddress")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProofOfOwnership")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("QualityCertificates")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SignatureCircular")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SocialSecurityRegistration")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TaxRegistration")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TradeRegistryGazette")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TrademarkCertificate")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("data.StoreShip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Block")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("StoreShip");
                });

            modelBuilder.Entity("data.TaskCategories", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryStructure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TaskFrameworkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WorkstationEmployeeGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TaskCategories");
                });

            modelBuilder.Entity("data.TaskFramework", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TaskFramework");
                });

            modelBuilder.Entity("data.TaskNotes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsTheNoteOk")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NoteCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TaskStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TaskNotes");
                });

            modelBuilder.Entity("data.TaskStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateInEditing")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateInProcess")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateToBeDone")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsInEditing")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsInProgress")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsNew")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsToBeDone")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PersonInChargeUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Priority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TaskCategoriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TaskDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaskStatus");
                });

            modelBuilder.Entity("data.UserShortcuts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ShortcutIcon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortcutName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortcutUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserShortcuts");
                });

            modelBuilder.Entity("data.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountActivationMailCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AccountActivationMailDeadline")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AccountActivationMailStatu")
                        .HasColumnType("bit");

                    b.Property<int>("AccountPasswordResetMailCode")
                        .HasColumnType("int");

                    b.Property<string>("BackgroundImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeaderMenuType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsActiveVendorStatu")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("TermsOfUse")
                        .HasColumnType("bit");

                    b.Property<bool?>("UserIsEmployee")
                        .HasColumnType("bit");

                    b.Property<string>("UserSponsorEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsersType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("WorkstationEmployeeGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("data.UsersRoles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UsersRoles");
                });

            modelBuilder.Entity("data.WorkstationEmployeeGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateAtDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkstationEmployeeGroup");
                });

            modelBuilder.Entity("data.Addresses", b =>
                {
                    b.OwnsOne("data._Shared.AddressInfo", "AddressInfo", b1 =>
                        {
                            b1.Property<Guid>("AddressesId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Address")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("GoogleMyBusinessAccountLink")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("float");

                            b1.Property<string>("MapTitle")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("State")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ZipCode")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AddressesId");

                            b1.ToTable("Addresses");

                            b1.WithOwner()
                                .HasForeignKey("AddressesId");
                        });

                    b.OwnsOne("data._Shared.IsDeleted", "IsDeleted", b1 =>
                        {
                            b1.Property<Guid>("AddressesId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("DeletedAtDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool?>("IsDeletedStatu")
                                .HasColumnType("bit");

                            b1.HasKey("AddressesId");

                            b1.ToTable("Addresses");

                            b1.WithOwner()
                                .HasForeignKey("AddressesId");
                        });

                    b.Navigation("AddressInfo");

                    b.Navigation("IsDeleted");
                });

            modelBuilder.Entity("data.FriendShip", b =>
                {
                    b.OwnsOne("data._Shared.IsDeleted", "IsDeleted", b1 =>
                        {
                            b1.Property<Guid>("FriendShipId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("DeletedAtDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool?>("IsDeletedStatu")
                                .HasColumnType("bit");

                            b1.HasKey("FriendShipId");

                            b1.ToTable("FriendShip");

                            b1.WithOwner()
                                .HasForeignKey("FriendShipId");
                        });

                    b.Navigation("IsDeleted");
                });

            modelBuilder.Entity("data.Store", b =>
                {
                    b.OwnsOne("data._Shared.AddressInfo", "AddressInfo", b1 =>
                        {
                            b1.Property<Guid>("StoreId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Address")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("GoogleMyBusinessAccountLink")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("float");

                            b1.Property<string>("MapTitle")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("State")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ZipCode")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("StoreId");

                            b1.ToTable("Stores");

                            b1.WithOwner()
                                .HasForeignKey("StoreId");
                        });

                    b.OwnsOne("data._Shared.ContactInformation", "ContactInformation", b1 =>
                        {
                            b1.Property<Guid>("StoreId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Behance")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CountryPhoneCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Discord")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Email")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Facebook")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FullPhoneNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("GitHub")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Instagram")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool?>("IsActiveBehance")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveDiscord")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveEmail")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveFacebook")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveGitHub")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveInstagram")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveKakaoTalk")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveLine")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveLinkedin")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActivePhoneNumber")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActivePinterest")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveReddit")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveTelegram")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveTikTok")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveUserWebSite")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveVKontakte")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveWeChat")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveWeibo")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveWhatsApp")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveX")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveYouTube")
                                .HasColumnType("bit");

                            b1.Property<string>("KakaoTalk")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Line")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Linkedin")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("PhoneEmailConfirmed")
                                .HasColumnType("bit");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("PhoneNumberConfirmed")
                                .HasColumnType("bit");

                            b1.Property<string>("Pinterest")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Reddit")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Telegram")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TikTok")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("UserWebSite")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("VKontakte")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("WeChat")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Weibo")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("WhatsApp")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("X")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("YouTube")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("StoreId");

                            b1.ToTable("Stores");

                            b1.WithOwner()
                                .HasForeignKey("StoreId");
                        });

                    b.OwnsOne("data._Shared.IsDeleted", "IsDeleted", b1 =>
                        {
                            b1.Property<Guid>("StoreId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("DeletedAtDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool?>("IsDeletedStatu")
                                .HasColumnType("bit");

                            b1.HasKey("StoreId");

                            b1.ToTable("Stores");

                            b1.WithOwner()
                                .HasForeignKey("StoreId");
                        });

                    b.OwnsOne("data._Shared.ProfileCoverGallery", "ProfileCoverGallery", b1 =>
                        {
                            b1.Property<Guid>("StoreId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CoverImagePath")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ProfileImagePath")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("StoreId");

                            b1.ToTable("Stores");

                            b1.WithOwner()
                                .HasForeignKey("StoreId");
                        });

                    b.OwnsOne("data._Shared.WorkingHours", "WorkingHours", b1 =>
                        {
                            b1.Property<Guid>("StoreId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<TimeOnly?>("FinishTimeFriday")
                                .HasColumnType("time");

                            b1.Property<TimeOnly?>("FinishTimeMonday")
                                .HasColumnType("time");

                            b1.Property<TimeOnly?>("FinishTimeSaturday")
                                .HasColumnType("time");

                            b1.Property<TimeOnly?>("FinishTimeSunday")
                                .HasColumnType("time");

                            b1.Property<TimeOnly?>("FinishTimeThursday")
                                .HasColumnType("time");

                            b1.Property<TimeOnly?>("FinishTimeTuesday")
                                .HasColumnType("time");

                            b1.Property<TimeOnly?>("FinishTimeWednesday")
                                .HasColumnType("time");

                            b1.Property<bool?>("IsActiveFriday")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveMonday")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveSaturday")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveSunday")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveThursday")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveTuesday")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveWednesday")
                                .HasColumnType("bit");

                            b1.Property<TimeOnly?>("StartTimeFriday")
                                .HasColumnType("time");

                            b1.Property<TimeOnly?>("StartTimeMonday")
                                .HasColumnType("time");

                            b1.Property<TimeOnly?>("StartTimeSaturday")
                                .HasColumnType("time");

                            b1.Property<TimeOnly?>("StartTimeSunday")
                                .HasColumnType("time");

                            b1.Property<TimeOnly?>("StartTimeThursday")
                                .HasColumnType("time");

                            b1.Property<TimeOnly?>("StartTimeTuesday")
                                .HasColumnType("time");

                            b1.Property<TimeOnly?>("StartTimeWednesday")
                                .HasColumnType("time");

                            b1.HasKey("StoreId");

                            b1.ToTable("Stores");

                            b1.WithOwner()
                                .HasForeignKey("StoreId");
                        });

                    b.Navigation("AddressInfo");

                    b.Navigation("ContactInformation");

                    b.Navigation("IsDeleted");

                    b.Navigation("ProfileCoverGallery");

                    b.Navigation("WorkingHours");
                });

            modelBuilder.Entity("data.StoreShip", b =>
                {
                    b.OwnsOne("data._Shared.IsDeleted", "IsDeleted", b1 =>
                        {
                            b1.Property<Guid>("StoreShipId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("DeletedAtDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool?>("IsDeletedStatu")
                                .HasColumnType("bit");

                            b1.HasKey("StoreShipId");

                            b1.ToTable("StoreShip");

                            b1.WithOwner()
                                .HasForeignKey("StoreShipId");
                        });

                    b.Navigation("IsDeleted");
                });

            modelBuilder.Entity("data.TaskCategories", b =>
                {
                    b.OwnsOne("data._Shared.IsDeleted", "IsDeleted", b1 =>
                        {
                            b1.Property<Guid>("TaskCategoriesId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("DeletedAtDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool?>("IsDeletedStatu")
                                .HasColumnType("bit");

                            b1.HasKey("TaskCategoriesId");

                            b1.ToTable("TaskCategories");

                            b1.WithOwner()
                                .HasForeignKey("TaskCategoriesId");
                        });

                    b.Navigation("IsDeleted");
                });

            modelBuilder.Entity("data.TaskFramework", b =>
                {
                    b.OwnsOne("data._Shared.IsDeleted", "IsDeleted", b1 =>
                        {
                            b1.Property<Guid>("TaskFrameworkId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("DeletedAtDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool?>("IsDeletedStatu")
                                .HasColumnType("bit");

                            b1.HasKey("TaskFrameworkId");

                            b1.ToTable("TaskFramework");

                            b1.WithOwner()
                                .HasForeignKey("TaskFrameworkId");
                        });

                    b.Navigation("IsDeleted");
                });

            modelBuilder.Entity("data.TaskNotes", b =>
                {
                    b.OwnsOne("data._Shared.IsDeleted", "IsDeleted", b1 =>
                        {
                            b1.Property<Guid>("TaskNotesId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("DeletedAtDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool?>("IsDeletedStatu")
                                .HasColumnType("bit");

                            b1.HasKey("TaskNotesId");

                            b1.ToTable("TaskNotes");

                            b1.WithOwner()
                                .HasForeignKey("TaskNotesId");
                        });

                    b.Navigation("IsDeleted");
                });

            modelBuilder.Entity("data.TaskStatus", b =>
                {
                    b.OwnsOne("data._Shared.IsDeleted", "IsDeleted", b1 =>
                        {
                            b1.Property<Guid>("TaskStatusId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("DeletedAtDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool?>("IsDeletedStatu")
                                .HasColumnType("bit");

                            b1.HasKey("TaskStatusId");

                            b1.ToTable("TaskStatus");

                            b1.WithOwner()
                                .HasForeignKey("TaskStatusId");
                        });

                    b.Navigation("IsDeleted");
                });

            modelBuilder.Entity("data.Users", b =>
                {
                    b.OwnsOne("data._Shared.ContactInformation", "ContactInformation", b1 =>
                        {
                            b1.Property<Guid>("UsersId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Behance")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CountryPhoneCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Discord")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Email")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Facebook")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FullPhoneNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("GitHub")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Instagram")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool?>("IsActiveBehance")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveDiscord")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveEmail")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveFacebook")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveGitHub")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveInstagram")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveKakaoTalk")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveLine")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveLinkedin")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActivePhoneNumber")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActivePinterest")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveReddit")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveTelegram")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveTikTok")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveUserWebSite")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveVKontakte")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveWeChat")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveWeibo")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveWhatsApp")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveX")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveYouTube")
                                .HasColumnType("bit");

                            b1.Property<string>("KakaoTalk")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Line")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Linkedin")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("PhoneEmailConfirmed")
                                .HasColumnType("bit");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("PhoneNumberConfirmed")
                                .HasColumnType("bit");

                            b1.Property<string>("Pinterest")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Reddit")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Telegram")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TikTok")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("UserWebSite")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("VKontakte")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("WeChat")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Weibo")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("WhatsApp")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("X")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("YouTube")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsersId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UsersId");
                        });

                    b.OwnsOne("data._Shared.ProfileCoverGallery", "ProfileCoverGallery", b1 =>
                        {
                            b1.Property<Guid>("UsersId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CoverImagePath")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ProfileImagePath")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsersId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UsersId");
                        });

                    b.OwnsOne("data._Shared.IsPrivateOrPublic", "IsPrivateOrPublic", b1 =>
                        {
                            b1.Property<Guid>("UsersId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool?>("IsAiTrainingAllowed")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsAllowComments")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsAllowDirectMessages")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsAllowFriendRequest")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsAllowPostDownloading")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsAllowPostsView")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsAllowStorySharing")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsAllowTagging")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsAllowVideoCalls")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsAllowVoiceCalls")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsDataCollectionAllowed")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsEmailNotificationEnabled")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsLocationVisible")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsPersonalizedAdsEnabled")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsProfilePublic")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsPushNotificationEnabled")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsReadReceiptsEnabled")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsSearchEngineIndexingAllowed")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsShowFollowerCount")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsShowFollowerList")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsShowFollowingList")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsShowLastSeen")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsShowOnlineStatus")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsSmsNotificationEnabled")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsTwoFactorAuthEnabled")
                                .HasColumnType("bit");

                            b1.HasKey("UsersId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UsersId");
                        });

                    b.OwnsOne("data._Shared.UserRolesAccessPermissions", "UserRolesAccessPermissions", b1 =>
                        {
                            b1.Property<Guid>("UsersId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool?>("IsItStaff")
                                .HasColumnType("bit");

                            b1.HasKey("UsersId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UsersId");
                        });

                    b.Navigation("ContactInformation");

                    b.Navigation("IsPrivateOrPublic");

                    b.Navigation("ProfileCoverGallery");

                    b.Navigation("UserRolesAccessPermissions");
                });

            modelBuilder.Entity("data.WorkstationEmployeeGroup", b =>
                {
                    b.OwnsOne("data._Shared.AddressInfo", "AddressInfo", b1 =>
                        {
                            b1.Property<Guid>("WorkstationEmployeeGroupId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Address")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("GoogleMyBusinessAccountLink")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("float");

                            b1.Property<string>("MapTitle")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("State")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ZipCode")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("WorkstationEmployeeGroupId");

                            b1.ToTable("WorkstationEmployeeGroup");

                            b1.WithOwner()
                                .HasForeignKey("WorkstationEmployeeGroupId");
                        });

                    b.OwnsOne("data._Shared.ContactInformation", "ContactInformation", b1 =>
                        {
                            b1.Property<Guid>("WorkstationEmployeeGroupId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Behance")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CountryPhoneCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Discord")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Email")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Facebook")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FullPhoneNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("GitHub")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Instagram")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool?>("IsActiveBehance")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveDiscord")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveEmail")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveFacebook")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveGitHub")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveInstagram")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveKakaoTalk")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveLine")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveLinkedin")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActivePhoneNumber")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActivePinterest")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveReddit")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveTelegram")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveTikTok")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveUserWebSite")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveVKontakte")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveWeChat")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveWeibo")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveWhatsApp")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveX")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveYouTube")
                                .HasColumnType("bit");

                            b1.Property<string>("KakaoTalk")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Line")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Linkedin")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("PhoneEmailConfirmed")
                                .HasColumnType("bit");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("PhoneNumberConfirmed")
                                .HasColumnType("bit");

                            b1.Property<string>("Pinterest")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Reddit")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Telegram")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TikTok")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("UserWebSite")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("VKontakte")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("WeChat")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Weibo")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("WhatsApp")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("X")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("YouTube")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("WorkstationEmployeeGroupId");

                            b1.ToTable("WorkstationEmployeeGroup");

                            b1.WithOwner()
                                .HasForeignKey("WorkstationEmployeeGroupId");
                        });

                    b.OwnsOne("data._Shared.IsDeleted", "IsDeleted", b1 =>
                        {
                            b1.Property<Guid>("WorkstationEmployeeGroupId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("DeletedAtDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool?>("IsDeletedStatu")
                                .HasColumnType("bit");

                            b1.HasKey("WorkstationEmployeeGroupId");

                            b1.ToTable("WorkstationEmployeeGroup");

                            b1.WithOwner()
                                .HasForeignKey("WorkstationEmployeeGroupId");
                        });

                    b.OwnsOne("data._Shared.ProfileCoverGallery", "ProfileCoverGallery", b1 =>
                        {
                            b1.Property<Guid>("WorkstationEmployeeGroupId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CoverImagePath")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ProfileImagePath")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("WorkstationEmployeeGroupId");

                            b1.ToTable("WorkstationEmployeeGroup");

                            b1.WithOwner()
                                .HasForeignKey("WorkstationEmployeeGroupId");
                        });

                    b.Navigation("AddressInfo");

                    b.Navigation("ContactInformation");

                    b.Navigation("IsDeleted");

                    b.Navigation("ProfileCoverGallery");
                });
#pragma warning restore 612, 618
        }
    }
}
