// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace data.Migrations
{
    [DbContext(typeof(_ApplicationConnectionDb))]
    [Migration("20260118223520_3")]
    partial class _3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("data.CategoriesAz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CategoriesAz");
                });

            modelBuilder.Entity("data.CategoriesDe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CategoriesDe");
                });

            modelBuilder.Entity("data.CategoriesEn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CategoriesEn");
                });

            modelBuilder.Entity("data.CategoriesEs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CategoriesEs");
                });

            modelBuilder.Entity("data.CategoriesFr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CategoriesFr");
                });

            modelBuilder.Entity("data.CategoriesHi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CategoriesHi");
                });

            modelBuilder.Entity("data.CategoriesPt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CategoriesPt");
                });

            modelBuilder.Entity("data.CategoriesRu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CategoriesRu");
                });

            modelBuilder.Entity("data.CategoriesTr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CategoriesTr");
                });

            modelBuilder.Entity("data.CategoriesZh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CategoriesZh");
                });

            modelBuilder.Entity("data.Cities", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("country_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("country_id")
                        .HasColumnType("int");

                    b.Property<string>("country_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("latitude")
                        .HasColumnType("float");

                    b.Property<int?>("level")
                        .HasColumnType("int");

                    b.Property<double?>("longitude")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("native")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("parent_id")
                        .HasColumnType("int");

                    b.Property<long?>("population")
                        .HasColumnType("bigint");

                    b.Property<string>("state_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("state_id")
                        .HasColumnType("int");

                    b.Property<string>("state_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("timezone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("translations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wikiDataId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("data.Country", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<long?>("area_sq_km")
                        .HasColumnType("bigint");

                    b.Property<string>("capital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currency_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currency_symbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emoji")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emojiU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("flag")
                        .HasColumnType("bit");

                    b.Property<long?>("gdp")
                        .HasColumnType("bigint");

                    b.Property<string>("iso2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("iso3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("latitude")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal?>("longitude")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("native")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numeric_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phonecode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("population")
                        .HasColumnType("bigint");

                    b.Property<string>("postal_code_format")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("postal_code_regex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("region_id")
                        .HasColumnType("int");

                    b.Property<string>("subregion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("subregion_id")
                        .HasColumnType("int");

                    b.Property<string>("timezones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tld")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("translations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("wikiDataId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("data.Logs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Languages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referrer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("data.Regions", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("flag")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("translations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_at")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("wikiDataId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("data.States", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("country_code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("country_code");

                    b.Property<int?>("country_id")
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<string>("country_name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("country_name");

                    b.Property<string>("fips_code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("fips_code");

                    b.Property<string>("iso2")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("iso2");

                    b.Property<string>("iso3166_2")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("iso3166_2");

                    b.Property<decimal>("latitude")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<int?>("level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<decimal>("longitude")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<string>("name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("native")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("native");

                    b.Property<int?>("parent_id")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<long?>("population")
                        .HasColumnType("bigint")
                        .HasColumnName("population");

                    b.Property<string>("timezone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("timezone");

                    b.Property<string>("translations")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("translations");

                    b.Property<string>("type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.Property<string>("wikiDataId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("wikiDataId");

                    b.HasKey("id");

                    b.ToTable("States");
                });

            modelBuilder.Entity("data.UserShortcuts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ShortcutIcon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortcutName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortcutUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserShortcuts");
                });

            modelBuilder.Entity("data.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BackgroundImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeaderMenuType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActiveVendorStatu")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TermsOfUse")
                        .HasColumnType("bit");

                    b.Property<string>("UsersType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("data.Users", b =>
                {
                    b.OwnsOne("data._Shared.AddressInfo", "AddressInfo", b1 =>
                        {
                            b1.Property<Guid>("UsersId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Address")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("GoogleMyBusinessAccountLink")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("float");

                            b1.Property<string>("MapTitle")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("State")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ZipCode")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsersId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UsersId");
                        });

                    b.OwnsOne("data._Shared.ContactInformation", "ContactInformation", b1 =>
                        {
                            b1.Property<Guid>("UsersId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Behance")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CountryPhoneCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Discord")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Email")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Facebook")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("GitHub")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Instagram")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool?>("IsActiveBehance")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveDiscord")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveEmail")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveFacebook")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveGitHub")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveInstagram")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveKakaoTalk")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveLine")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveLinkedin")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActivePhoneNumber")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActivePinterest")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveReddit")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveTelegram")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveTikTok")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveUserWebSite")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveVKontakte")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveWeChat")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveWeibo")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveWhatsApp")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveX")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsActiveYouTube")
                                .HasColumnType("bit");

                            b1.Property<string>("KakaoTalk")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Line")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Linkedin")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("PhoneEmailConfirmed")
                                .HasColumnType("bit");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("PhoneNumberConfirmed")
                                .HasColumnType("bit");

                            b1.Property<string>("Pinterest")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Reddit")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Telegram")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TikTok")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("UserWebSite")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("VKontakte")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("WeChat")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Weibo")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("WhatsApp")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("X")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("YouTube")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsersId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UsersId");
                        });

                    b.OwnsOne("data._Shared.IsPrivateOrPublic", "IsPrivateOrPublic", b1 =>
                        {
                            b1.Property<Guid>("UsersId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool?>("IsAiTrainingAllowed")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsAllowComments")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsAllowDirectMessages")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsAllowFriendRequest")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsAllowPostDownloading")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsAllowPostsView")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsAllowStorySharing")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsAllowTagging")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsAllowVideoCalls")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsAllowVoiceCalls")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsDataCollectionAllowed")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsEmailNotificationEnabled")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsLocationVisible")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsPersonalizedAdsEnabled")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsProfilePublic")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsPushNotificationEnabled")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsReadReceiptsEnabled")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsSearchEngineIndexingAllowed")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsShowFollowerCount")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsShowFollowerList")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsShowFollowingList")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsShowLastSeen")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsShowOnlineStatus")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsSmsNotificationEnabled")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsTwoFactorAuthEnabled")
                                .HasColumnType("bit");

                            b1.HasKey("UsersId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UsersId");
                        });

                    b.OwnsOne("data._Shared.ProfileCoverGallery", "ProfileCoverGallery", b1 =>
                        {
                            b1.Property<Guid>("UsersId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CoverImagePath")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ProfileImagePath")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsersId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UsersId");
                        });

                    b.Navigation("AddressInfo")
                        .IsRequired();

                    b.Navigation("ContactInformation")
                        .IsRequired();

                    b.Navigation("IsPrivateOrPublic")
                        .IsRequired();

                    b.Navigation("ProfileCoverGallery")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
