<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Admin\az\" />
    <Folder Include="Admin\de\" />
    <Folder Include="Admin\en\" />
    <Folder Include="Admin\es\" />
    <Folder Include="Admin\fr\" />
    <Folder Include="Admin\hi\" />
    <Folder Include="Admin\pt\" />
    <Folder Include="Admin\ru\" />
    <Folder Include="Admin\tr\" />
    <Folder Include="Admin\zh\" />
    <Folder Include="Customer\az\" />
    <Folder Include="Customer\de\" />
    <Folder Include="Customer\en\" />
    <Folder Include="Customer\es\" />
    <Folder Include="Customer\fr\" />
    <Folder Include="Customer\hi\" />
    <Folder Include="Customer\pt\" />
    <Folder Include="Customer\ru\" />
    <Folder Include="Customer\tr\" />
    <Folder Include="Customer\zh\" />
    <Folder Include="Visitor\" />
    <Folder Include="Vendor\az\" />
    <Folder Include="Vendor\de\" />
    <Folder Include="Vendor\en\" />
    <Folder Include="Vendor\es\" />
    <Folder Include="Vendor\fr\" />
    <Folder Include="Vendor\hi\" />
    <Folder Include="Vendor\zh\" />
    <Folder Include="Vendor\tr\" />
    <Folder Include="Vendor\ru\" />
    <Folder Include="Vendor\pt\" />
    <Folder Include="_Shared\az\" />
    <Folder Include="_Shared\de\" />
    <Folder Include="_Shared\en\" />
    <Folder Include="_Shared\es\" />
    <Folder Include="_Shared\fr\" />
    <Folder Include="_Shared\hi\" />
    <Folder Include="_Shared\pt\" />
    <Folder Include="_Shared\ru\" />
    <Folder Include="_Shared\zh\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\api\api.csproj" />
    <ProjectReference Include="..\data\data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="_Shared\FaIcons.razor">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Update="_Shared\ThisPageIsBeingPrepared.razor">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
