<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
		<GenerateWebConfig>false</GenerateWebConfig>
		<UserSecretsId>df9a6562-6db3-4ba3-b1b3-350a64d71071</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
	  <Content Include="files\users\huseyindemirdoger1992%40gmail.com\documents\rss.xml" />
	  <Content Include="files\users\huseyindemirdoger1992%40gmail.com\others\rss.xml" />
	  <Content Include="files\users\huseyindemirdoger1992%40gmail.com\pictures\rss.xml" />
	  <Content Include="files\users\huseyindemirdoger1992%40gmail.com\videos\rss.xml" />
	  <Content Include="files\xml\sitemap\rss.xml" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\api\api.csproj" />
		<ProjectReference Include="..\data\data.csproj" />
		<ProjectReference Include="..\razor\razor.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Areas\Vendor\Controllers\" />
		<Folder Include="Areas\Vendor\Views\" />
	</ItemGroup>

	<ItemGroup>
		<None Update="web.config">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</None>
	</ItemGroup>


</Project>
